### ISSUE TITLE
Ignores entered name

### ISSUE THREAD

**Issue by Inrego** [interisti/vs-material-icons-generator#11]
### Installed product versions
- Visual Studio: VS Community 2017 v15.4.0
- This extension: 1.4

### Description
When adding icons, it uses the default generated name (from selected icon and size), ignoring the name I entered.

### Steps to recreate
1. Open window to add icon
2. Select an icon
3. Change size to 36dp
4. Remove the _36dp from the end of name
5. Add to project

### Current behavior
The added files still have _36dp appended in the end, even though I removed it from name before clicking add to project.

### Expected behavior
The name I changed to, should be used as base for file names.

**Comment by interisti** [comment]
@Inrego  Thanks for reporting the issue, its fixed and new version is published.
