### ISSUE TITLE
Freezing VS2015 1.5 

### ISSUE THREAD

**Issue by interCreaciones** [interisti/vs-material-icons-generator#14]
Installed product versions

    Visual Studio: 2015 
    This extension: 1.5

Description

After downloading the file the window is not closed, it freezes the VS 2015. When it returns the VS2015 accuses that it has a window still open in operation.
Steps to recreate

    Open extenstion
    Selected icon
    Freeze window
    button close and cross not working freezing VS2015

Current behavior

Freeze Vs2015

**Comment by interisti** [comment]
@interCreaciones 

it turns out Google material icons repo missing some icons in some sizes and plugin was not handling such responses and its freezes. 

should be fixed in latest version though. you can try, its v1.5.2
