### ISSUE TITLE
Can't install the package on Visual studio Mac

### ISSUE THREAD

**Issue by nivibhat** [interisti/vs-material-icons-generator#16]
### Installed product versions
- Visual Studio: [example 2015 Professional]
- This extension: [example 1.1.21]

### Description
I have downloaded vsix extension, but looks like we need mpak ext to install it on mac. is there any mpak available?

**Comment by interisti** [comment]
cause its Xamarin Studio with new name. I have a version of it here https://github.com/interisti/xs-material-icons-generator but it has not updated for years.
