### ISSUE TITLE
Image for ic_check_box_black_XXdp is Broken

### ISSUE THREAD

**Issue by brittonbeckham** [interisti/vs-material-icons-generator#17]
### Installed product versions
- Visual Studio: 2017 ent
- This extension: 1.5

### Description
`ic_check_box_black_xxdp` is not working. Image doesn't show in previewer and cannot `Add to Project` or image is corrupt when downloaded. 

### Steps to recreate
1. Open Extention
2. search "check box"
3. Click on any results
4. Attempt to add to project and it will either silent fail or download corrupt pngs.
5. I also tried other colors

### Current behavior
see above

### Expected behavior
Should download correct image at right dp setting.

**Comment by interisti** [comment]
Hi @brittonbeckham 

the issue there is that there is no other sizes of `ic_check_box` icon other then 24dp in Google's [repo](https://github.com/google/material-design-icons/tree/master/toggle/drawable-mdpi) so plugin is unable to download that icon.

I've updated the plugin to display a message for such cases.
