### ISSUE TITLE
All Icon requested white in for iOS are downloaded in black

### ISSUE THREAD

**Issue by KodaPOwER** [interisti/vs-material-icons-generator#18]
### Installed product versions
- Visual Studio: 15.5.5
- This extension: 1.5

### Description
When i download any icon in white color, the plugin download the black version

Here an example (ic_menu_white_24dp)
![ic_menu_white_24dp](https://user-images.githubusercontent.com/9638822/36211985-156f7eea-11a3-11e8-9088-9ed5ae6a83ea.png)

For android it work like a charm.

Any help?
Thanks

**Comment by interisti** [comment]
Hi @KodaPOwER 
thanks for report, try new version it should be fixed.

Cheers

**Comment by KodaPOwER** [comment]
Now it work as expected!
Thank you for the fix and for this little but great extension!
