### ISSUE TITLE
Unexpected character encountered while parsing value: <. Path ", line 0, position 0

### ISSUE THREAD

**Issue by weberhannes** [interisti/vs-material-icons-generator#20]
Visual Studio: 2017 Community
This extension: 1.5.3

### Description
The plugin works fine for a long time. Now I get the following error:
 
![grafik](https://user-images.githubusercontent.com/39127373/39819770-8f7248d8-53a4-11e8-98ee-b76a063582b8.png)

### Steps to recreate
1. Open the manager via right click on your solution (Android)
2. The manager windows comes up.
3. The error box appears.

**Comment by interisti** [comment]
Hi @weberhannes 
Thanks for reporting the bug. https://material.io was updated and the json file that contained the list of icons was changed. I've updated the extension to fix that, though there are some differences between json returned and actual icons in their repo, so some of the icons are missing but at least now extension is usable.

**Comment by weberhannes** [comment]
I checked the fix. Well done.
