### ISSUE TITLE
Some icons are missing

### ISSUE THREAD

**Issue by CarlosACepeda** [interisti/vs-material-icons-generator#24]
### Installed product versions
- Visual Studio: [2017 Enterprise]
- This extension: [1.6.3]

### Description
Missing icons

### Steps to recreate
1. Search for Icons:
example: 'battery_20' icon (https://material.io/tools/icons/?icon=battery_20&style=baseline)
![image](https://user-images.githubusercontent.com/21343483/43438562-7322bffa-9454-11e8-9e50-eee38928a11c.png)

### Current behavior
Not appearing, it's missing and several others.
![image](https://user-images.githubusercontent.com/21343483/43438582-944681f8-9454-11e8-870d-dd672922b5cd.png)

### Expected behavior
Missing icons should appear.

**Comment by interisti** [comment]
@CarlosACepeda 
Yeah, plugin was downloading list of icons from the previous version of the site `https://material.io/tools/icons`, then use repo to download actual images.

But with new version there are differences, some of the icons are missing in repo, so ....

**Comment by wollac11** [comment]
I am experiencing missing icons too only for me it is now all of them. Every single icon is missing and shows the error "Icon does not exists, try another size".

**Comment by interisti** [comment]
I've reverted back source to https://material.io/tools/icons/static/data.json and some of the icons are now displayed, though there are several which does not exist in google's repo.

So i'm closing this for now

**Comment by CarlosACepeda** [comment]
Okay! that's some bad news, keep up, this extension is very helpful anyway!
