### ISSUE TITLE
Installation under Visual Studio 2017 Professional not possible

### ISSUE THREAD

**Issue by StefanHHH** [interisti/vs-material-icons-generator#25]
### Installed product versions
- Visual Studio: 2017 Profesional
- This extension: 1.6.3

### Description
Installation under Visual Studio 2017 Professional fails. See Logfile below
31.10.2018 12:14:18 - Microsoft VSIX Installer
31.10.2018 12:14:18 - -------------------------------------------
31.10.2018 12:14:18 - Initializing Install...
31.10.2018 12:14:19 - Erweiterungsdetails...
31.10.2018 12:14:19 - 	Identifier      : e1bf5443-bf81-49e6-bc33-004e1f1f7b02
31.10.2018 12:14:19 - 	Name            : Material icons generator
31.10.2018 12:14:19 - 	Author          : Nika Nikabadze
31.10.2018 12:14:19 - 	Version         : 1.6.3
31.10.2018 12:14:19 - 	Description     : This plugin help you to add material design icons to your Android, iOS or UWP project
31.10.2018 12:14:19 - 	Locale          : en-US
31.10.2018 12:14:19 - 	MoreInfoURL     : https://github.com/interisti/vs-material-icons-generator
31.10.2018 12:14:19 - 	InstalledByMSI  : False
31.10.2018 12:14:19 - 	SupportedFrameworkVersionRange : [4.5,)
31.10.2018 12:14:19 - 
31.10.2018 12:14:19 - 	Unterstützte Produkte : 
31.10.2018 12:14:19 - 		Microsoft.VisualStudio.Community
31.10.2018 12:14:19 - 			Version : [14.0,16.0)
31.10.2018 12:14:19 - 
31.10.2018 12:14:19 - 	Verweise        : 
31.10.2018 12:14:19 - 
31.10.2018 12:14:19 - VSIXInstaller.NoApplicableSKUsException: Diese Erweiterung kann auf den derzeit installierten Produkten nicht installiert werden.
   bei VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   bei VSIXInstaller.App.InitializeInstall()
   bei System.Threading.Tasks.Task.InnerInvoke()
   bei System.Threading.Tasks.Task.Execute()

**Comment by interisti** [comment]
@StefanHHH Hey,

Just published a new version, Can you try again?

**Comment by StefanHHH** [comment]
Works perfect. Thank you
