### ISSUE TITLE
Add hex color input

### ISSUE THREAD

**Issue by andreaPorini** [interisti/vs-material-icons-generator#27]
### Installed product versions
- Visual Studio: [example 2017 Enterprise]
- This extension: [example 1.6.4]

Hi, great tool but i find the color selection quite tedious. 
Could you add some entry field for specify the hex code for the color of the icon?

Thank you,
Andrea

**Comment by joshuaquiz** [comment]
Yea, this would be really great for keeping your apps theme consistent.

**Comment by interisti** [comment]
hey guys,

Thanks for suggestion.

Can you check the CI build version if thats what you've asked for? 
http://vsixgallery.com/extension/e1bf5443-bf81-49e6-bc33-004e1f1f7b02/


Thanks.

**Comment by jdinnen** [comment]
This worked well for me, I needed to export them in a particular hex color. Make it live!

**Comment by interisti** [comment]
published v1.8.0
