### ISSUE TITLE
Specify themes for material icons

### ISSUE THREAD

**Issue by LeoJHarris** [interisti/vs-material-icons-generator#32]
Hi there great plugin, a nice enhancement request to be able to select the theme i.e. Filled, outlined, Rounded, Two tone, Sharp. Does the source for these images have the ability to specify this?

**Comment by interisti** [comment]
Thanks @LeoJHarris  for suggestion,

though last time i checked the [google's](https://github.com/google/material-design-icons) repo, there were none of those. The way plugin works currently is, download images from google's repo and then change color if its not white or black. So it depends entirely whether those files exists or not.

**Comment by interisti** [comment]
Hey,

I've just published the V2 version which adds the themes. :tada: 

Thanks.

**Comment by LeoJHarris** [comment]
@interisti 🥇
