### ISSUE TITLE
Error reading JObject from JsonReader. Path '', line 0, position 0

### ISSUE THREAD

**Issue by tblack2200** [interisti/vs-material-icons-generator#33]
### Installed product versions
- Visual Studio: [2019 Professional]
- This extension: [Material Icon Generator 1.7.0]

### Description
When I open the Material Icon Generator, I get this error
Error reading JObject from JsonReader. Path '', line 0, position 0

### Steps to recreate
Installed the extension and opened it

**Comment by interisti** [comment]
@tblack2200  can you check this url https://material.io/tools/icons/static/data.json in browser, if it loads the valid json
