### ISSUE TITLE
Error when opening the extension in VS (HRESULT 0x80072ee4)

### ISSUE THREAD

**Issue by lukashoferdev** [interisti/vs-material-icons-generator#34]
### Installed product versions
- Microsoft Visual Studio Community 2017, Version 15.9.14
- This extension, Version 1.8.60

### Description
When I click right on the "Manage Material Icons..." it always throws the error "HRESULT 0x80072ee4".

### Possible workaround
I tried a lot of things, uninstall, reinstall, update... And googled it, but no workaround worked for me.
I also tried to uninstall and reinstall from the VSGallery (https://marketplace.visualstudio.com/items?itemName=nikainteristi.Materialiconsgenerator)

**Comment by interisti** [comment]
hey @lukasbfh 

trying to replicate that error. I've updated the VS to that exact version and tried 1.8.0 version and it worked for Xamarin.Android project. Does that issue happens on Xamarin.Android only? Xamarin.iOS only? UWP only? all of them?

**Comment by lukashoferdev** [comment]
I only need it for Xamarin.Android, so I only tested it with this. I tried also to create a new project, it didn't worked.

**Comment by interisti** [comment]
I was not able to reproduce that issue locally, so can you try to uninstall existing version and install attached version?  
https://drive.google.com/open?id=1pxHDHfr3s-EHGxlMviewQ2x1IICBCerX

it should output the error message and stacktrace in VS's output pane, can you paste it here please?

**Comment by lukashoferdev** [comment]
This was the output: 
DEBUG MESSAGE: test
DEBUG STACK:    bei MaterialIconsGenerator.VSPackage.<InitializeAsync>d__1.MoveNext() in C:\projects\vs-material-icons-generator\src\MaterialIconsGenerator\VSPackage.cs:Zeile 66.
Sorry my VS is in german....
And when I open the extension the following error appears: 
"Die Ausnahme "Unbekannten Softwarefehler" (0xe0434352) ist in der Anwendung an der Stelle 0x00000000766A3442 aufgetreten."

**Comment by interisti** [comment]
@lukasbfh can you try this version please?
https://drive.google.com/open?id=12Fn-9xE5qfQIcRR3XTIHrJpDrHWSVGk-

**Comment by lukashoferdev** [comment]
With this version, no stacktrace is shown and VS is restarting after opening the extension.

**Comment by interisti** [comment]
Hey,

I've just published the V2 version which should fix any VS19 issues. can you try it and reopen this if its still an issue.

Thanks.
