### ISSUE TITLE
Add Icons into mipmap Folder 

### ISSUE THREAD

**Issue by yrguativa** [interisti/vs-material-icons-generator#35]
### Installed product versions
- Visual Studio: [2017]
- This extension: [1.8.0]

### Description
I am work in xamarin Android and the folder are not called Drawable but mipmap

### Current behavior
When add a icon, the extension create folder drawable-hdpi, drawable-mdpi, and so on.

### Expected behavior
The extension should add the icons into folder nipmap-hdpi, mipmap-mdpi, and so on.

**Comment by interisti** [comment]
Hey,

I've just published the V2 which adds the missing resource dirs (mipmap, ...)
