### ISSUE TITLE
Error Opening Extension

### ISSUE THREAD

**Issue by rkralston** [interisti/vs-material-icons-generator#36]
### Installed product versions
- Visual Studio: 2019 VS Enterprise 16.3.5 with .Net 4.7.03062
- This extension: 1.8.0

### Description
Error when opening extension.

### Steps to recreate
1. Right click on project
2. Select Manage Material Icons ...

### Current behavior
Error dialog with empty extension dialog

Unexpected character encountered while parsing value: <. Path ", line 0, position 0.

### Expected behavior
Dialog with icons.

**Comment by interisti** [comment]
Hello,

The only time i could reproduce this on my machine was when i had no internet connection. Also i've published the new version which adds icon themes. if there will be same issue can you try to access https://www.vs-material-icons-generator.com. I'm closing this issue for now. Please open it again if issue still  exists.
