### ISSUE TITLE
Support iOS and UWP

### ISSUE THREAD

**Issue by YZahringer** [interisti/vs-material-icons-generator#4]
### Description
Support iOS and UWP projects.

iOS:
- Add images to Resources folder with iconName.png, iconName@2x.png and iconName@3x.png

UWP:
- Add image in root of project

**Comment by Inrego** [comment]
I would very much like this aswell. It's not very useful for me when it's Android-only.

**Comment by interisti** [comment]
@YZahringer  @Inrego 
Hey guys, thanks for suggestion.

Currently doing some refactoring to make such changes easily, in the future. (first version was written badly).
Then will work on iOS , though, can't tell you when it will be ready.

**Comment by interisti** [comment]
@YZahringer @Inrego

just added support for iOS and its published.
will add UWP support soon, probably this weekend.

Feedback is much appreciated.

**Comment by Inrego** [comment]
Hey.

My project also includes UWP, so without UWP support I will probably just go with manual way. I'll be glad to give it a try if/when you add UWP as well.

**Comment by interisti** [comment]
Hey guys

i was researching the guidelines for sizes and densities for UWP projects, as i have never worked with UWP before. In 'Google Material icons" repo, there are clear distinction between sizes and densities for android and iOS, no UWP though. 
I found this https://docs.microsoft.com/en-us/windows/uwp/controls-and-patterns/tiles-and-notifications-app-assets. need advice or resources (even better) about sizes and densities that is needed for UWP.

**Comment by Inrego** [comment]
Personally, I just use the @2 file from web folder, and remove the @2 from
filename. It's placed in project root.

**Comment by interisti** [comment]
check out new version.

**Comment by interisti** [comment]
@YZahringer should we close this ?

**Comment by YZahringer** [comment]
@interisti yes, thank you 👍
