### ISSUE TITLE
Material Icons Generator window stay empty

### ISSUE THREAD

**Issue by jb8572** [interisti/vs-material-icons-generator#42]
### Installed product versions
- Visual Studio: Studio Professional 2019 Version 16.7.3
- This extension: 2.1.0

### Steps to recreate
1. Right click on Xamarin.Android or Xamarin.iOS project
2. click "Manage Material Icon..."

### Current behavior
The window opens but stay empty

![image](https://user-images.githubusercontent.com/24377857/101045424-44a02800-354e-11eb-99a4-fe2436435a7a.png)

### Expected behavior
The window opens and is populated

**Comment by interisti** [comment]
Can you check if you have access to https://www.vs-material-icons-generator.com/icon-providers/google/assets/maps/drawable-hdpi/material-icons/360_48dp.png url

**Comment by jb8572** [comment]
No, I do not have access to this URL.  So I guess the problem is on my end...

Thanks for your quick reply
