### ISSUE TITLE
Freezing VS2017 1.5

### ISSUE THREAD

**Issue by moreirawebmaster** [interisti/vs-material-icons-generator#5]
### Installed product versions
- Visual Studio: 2017 Community 1.5(26430.12)
- This extension: 1.1.3

### Description
After downloading the file the window is not closed, it freezes the VS 2017. When it returns the VS2017 accuses that it has a window still open in operation.

### Steps to recreate
1. Open extenstion
2. Selected icon
3. Freeze window
4.  button close and cross not working freezing VS2017

### Current behavior
Freeze Vs2017

**Comment by interisti** [comment]
@moreirawebmaster 
Hi, can you try it again. I just updated a version.
